## parameters of the Milky Way + LMC potential for the case of moving LMC and evolving potentials of both MW halo and LMC
## Units: length=1 kpc, velocity=1 km/s, mass=232500 Msun, G=1

### parameters of halo density profile
[potential LMC]
file = lmc00.pot
